baseURL = "https://guersam.com/"
title = "guersam.com"
copyright = "Copyright &copy; 2018 guersam"

DefaultContentLanguage = "ko"
hasCJKLanguage = true

theme = "kiera"

pygmentsCodeFences = true
pygmentsStyle = "trac"

paginate = 3

enableEmoji = true

googleAnalytics = "UA-40336130-4"

[languages]
[languages.ko]
weight = 1

[languages.en]
weight = 2

[author]
  name = "guersam"
  github = "guersam"
  twitter = "guersam"

[params]
  tagline = "personal blog"
