DefaultContentLanguage = "ko"

baseURL = "https://guersam.com/"
title = "guersam.com"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true

googleAnalytics = "UA-40336130-4"

[languages]
[languages.ko]
weight = 1

[languages.en]
weight = 2

[author]
  name = "guersam"
  github = "guersam"
  twitter = "guersam"

[params]
  tagline = "personal blog"
